train_test_split:
  test_size: 0.2  # 20% of data will be used for testing
  random_state: 42  # Ensures reproducibility
  stratify: True  # Ensures equal class distribution

scaling:
  method: "StandardScaler"  # Options: "StandardScaler", "MinMaxScaler"
  apply_to: ["Age", "Height", "BMI", "FCVC", "NCP", "CH2O", "FAF", "TUE"]  # Features to scale

models:
  logistic_regression:
    penalty: "l2"
    solver: "liblinear"
    max_iter: 100
    C: 1.0  # Regularization strength

  decision_tree:
    criterion: "gini"
    max_depth: 5
    min_samples_split: 2
    min_samples_leaf: 1  # Minimum number of samples per leaf

evaluation_metrics:
  accuracy: True
  precision: True
  recall: True
  f1_score: True

inference_sample:
  columns: 
    - "Age"
    - "Height"
    - "BMI"
    - "FCVC"
    - "NCP"
    - "CH2O"
    - "FAF"
    - "TUE"
    - "Gender_Male"
    - "family_history_yes"
    - "FAVC_yes"
    - "CAEC_Sometimes"
    - "SMOKE_yes"
    - "CALC_Sometimes"
  values: [25, 1.75, 22.0, 2, 3, 2.0, 1, 0, 1, 0, 0, 1, 0, 1]
